name: MMCplugin
version: '${project.version}'
main: ga.denis.mmcplugin.MMCplugin
api-version: 1.19
authors: [ DenisOS ]
description: Main MMC plugin
commands:
  skywars:
    description: Controls skywars minigame
    usage: /<command> [action] [parameters]
    permission: mmcplugin.use
  parkour:
    description: Controls parkour minigame
    usage: /<command> [action] [parameters]
    permission: mmcplugin.use
  ghostblock:
    description: Places a ghost block to your location
    usage: /<command>
    permission: mmcplugin.use
  piston:
    description: Moves the block below you upwards
    usage: /<command>
    permission: mmcplugin.use