name: MMCplugin
version: '${project.version}'
main: ga.denis.mmcplugin.MMCplugin
api-version: 1.19
authors: [ DenisOS ]
description: Main MMC plugin
commands:
  skywars:
    description: Controls skywars minigame
    usage: /<command> [action] [parameters]
    permission: mmcplugin.use
  parkour:
    description: Controls parkour minigame
    usage: /<command> [action] [parameters]
    permission: mmcplugin.use
