name: MMCplugin
version: '${project.version}'
main: ga.denis.mmcplugin.MMCplugin
api-version: 1.19
authors: [ DenisOS ]
description: Main MMC plugin
commands:
  zone:
    description: Changes skywars zone size
    usage: /<command> [size]
    permission: mmcplugin.use
